global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "api"
    static_configs:
      - targets: ["api1:8080", "api2:8080"]
  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus:9090"]
