CREATE DATABASE `url-shortener` ;
use `url-shortener`;

SET FOREIGN_KEY_CHECKS = 0;
DROP TABLE IF EXISTS `url`;

CREATE TABLE url (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME NULL,
    shot_url VARCHAR(255),
    original_url VARCHAR(255) UNIQUE,
);
